<?php

class countries extends Model {

    protected $table = 'countries';

    public function create(array $data = null)
    {
        parent::create($data); // TODO: Change the autogenerated stub
    }

    public function update(array $data = null)
    {
        parent::update($data); // TODO: Change the autogenerated stub
    }

}